name: "[CI] AdditionalAuthorizationHandler"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"

env:
  CI: "true"
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 18.17.1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_app:
    uses: ./.github/workflows/build_app.yml
    secrets: inherit
    name: Build test application

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: OpenSourcePolitics/lint-action@master
        with:
          ruby_version: ${{ env.RUBY_VERSION }}
          node_version: ${{ env.NODE_VERSION }}

  tests:
    name: Tests
    needs: build_app
    uses: ./.github/workflows/test_app.yml
    with:
      test_command: "bundle exec rspec --exclude-pattern 'spec/system/**/*_spec.rb'"
    secrets: inherit

  system_tests:
    name: System tests
    needs: build_app
    uses: ./.github/workflows/test_app.yml
    with:
      test_command: "bundle exec rspec spec/system"
    secrets: inherit
