name: "[CI] AdditionalAuthorizationHandler"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"

env:
  CI: "true"
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 18.17.1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_app:
    uses: ./.github/workflows/build_app.yml
    secrets: inherit
    name: Build test application

  main:
    strategy:
      fail-fast: false
      matrix:
        test:
          - command: bundle exec parallel_test --type rspec --pattern spec/ --exclude-pattern spec/system
            name: "Unit tests"
          - command: bundle exec parallel_test --type rspec --pattern spec/system --exclude-pattern spec/system/admin
            name: "System tests"
      needs: build_app
      name: ${{ matrix.test.name }}
      uses: ./.github/workflows/test_app.yml
      secrets: inherit
      with:
        working-directory: "decidim-module-addtional_authorization_handler"
        test_command: ${{ matrix.test.command }}
